create table public.user_vocabulary (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  word text not null,
  meaning_en text,
  meaning_zh text,
  example text,
  constraint user_vocabulary_user_id_word_key unique (user_id, word)
);

alter table public.user_vocabulary enable row level security;

create policy "Users can insert their own vocabulary."
  on public.user_vocabulary for insert
  with check ( auth.uid() = user_id );

create policy "Users can view their own vocabulary."
  on public.user_vocabulary for select
  using ( auth.uid() = user_id );

create policy "Users can update their own vocabulary."
  on public.user_vocabulary for update
  using ( auth.uid() = user_id );

create policy "Users can delete their own vocabulary."
  on public.user_vocabulary for delete
  using ( auth.uid() = user_id );
